name: Test

on: [push, pull_request]

env:
  GO111MODULE: on

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run tests
      run: go list -v ./... | grep -vE '(tests|examples)$' | xargs go test -timeout 30s -v
      env:
        GOFLAGS: "-mod=vendor"
